" Setup NeoBundle  ----------------------------------------------------------{{{
" Note: Skip initialization for vim-tiny or vim-small.

if 0 | endif

if has('vim_starting')
    if &compatibile
       set nocompatibile
       endif
endif

" Required:
set runtimepath+=~/.nvim/bundle/neobundle.vim/

" Required:
call neobundle#begin(expand('~/.nvim/bundle/'))
" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!


" Colorschemes
NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'jonathanfilip/vim-lucius'
NeoBundle 'mhartington/oceanic-next'
NeoBundle 'ujihisa/unite-colorscheme'

" HTML
NeoBundle 'othree/html5.vim'

" CSS
NeoBundle 'mutewinter/vim-css3-syntax'
NeoBundle 'groenewege/vim-less'
NeoBundle 'tpope/vim-haml'

" PHP
NeoBundle 'StanAngeloff/php.vim'
NeoBundle 'captbaritone/better-indent-support-for-php-with-html'
NeoBundle 'arnaud-lb/vim-php-namespace'
NeoBundle 'shawncplus/phpcomplete.vim'
NeoBundle 'dsawardekar/wordpress.vim'
"NeoBundle 'docteurklein/php-getter-setter.vim'
"NeoBundle 'm2mdas/phpcomplete-extended'

" Javascript
NeoBundle 'othree/yajs.vim'
NeoBundle 'othree/es.next.syntax.vim'
NeoBundle '1995eaton/vim-better-javascript-completion'
NeoBundle 'tobinvanpelt/vim-coffee-script'
NeoBundle 'curist/vim-angular-template'
NeoBundle 'ruanyl/vim-fixmyjs'
NeoBundle 'elzr/vim-json', {'autoload':{'filetypes':['json']}}
NeoBundle 'pangloss/vim-javascript'
NeoBundle 'marijnh/tern_for_vim'
NeoBundle 'othree/javascript-libraries-syntax.vim'

" Typescript
NeoBundle 'HerringtonDarkholme/yats.vim'
NeoBundle 'Quramy/tsuquyomi'

" Ruby on Rails
"NeoBundle 'vim-scripts/ruby-matchit'
NeoBundle 'vim-ruby/vim-ruby'
NeoBundle 'tpope/vim-rails'
NeoBundle 'thoughtbot/vim-rspec'

" Togglable panels
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'tpope/vim-vinegar'
NeoBundle 'vim-scripts/taglist.vim'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'ctrlpvim/ctrlp.vim'

" Autocomplete
NeoBundle 'Valloric/YouCompleteMe'
NeoBundle 'MarcWeber/vim-addon-mw-utils'
NeoBundle 'MarcWeber/vim-addon-manager'
NeoBundle 'tomtom/tlib_vim'

" Snippets
NeoBundle 'SirVer/ultisnips'
NeoBundle 'honza/vim-snippets'
NeoBundle 'garbas/vim-snipmate'

" Git helpers
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'jreybert/vimagit'
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'Xuyuanp/nerdtree-git-plugin'
NeoBundle 'https://github.com/jaxbot/github-issues.vim'
NeoBundle 'mattn/gist-vim.git'
NeoBundle 'rhysd/github-complete.vim'
NeoBundle 'junegunn/vim-github-dashboard'

" Untils
NeoBundle 'benekastah/neomake'
NeoBundle 'editorconfig/editorconfig-vim'
NeoBundle 'AndrewRadev/switch.vim'
NeoBundle 'christoomey/vim-tmux-navigator'
NeoBundle 'tmux-plugins/vim-tmux'
NeoBundle 'tmux-plugins/vim-tmux-focus-events'
NeoBundle 'bling/vim-airline'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tomtom/tcomment_vim'
NeoBundle 'mattn/emmet-vim'
NeoBundle 'Chiel92/vim-autoformat'
NeoBundle 'gorodinskiy/vim-coloresque'

" Shougo
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/unite-outline'
NeoBundle 'Shougo/vimfiler.vim'
NeoBundle 'Shougo/deoplete.nvim'
NeoBundle 'Shougo/neco-vim'
NeoBundle 'Shougo/neoinclude.vim'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }

" Indent Line
NeoBundle 'Yggdroot/indentLine'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'Valloric/MatchTagAlways'

" Markdown
"NeoBundle 'tpope/vim-markdown'
NeoBundle 'suan/vim-instant-markdown'

" Databases
NeoBundle 'im-scripts/SQLUtilities'
NeoBundle 'NagatoPain/AutoSQLUpperCase.vim'

" fzf
NeoBundle 'junegunn/fzf.vim'
NeoBundle 'junegunn/fzf', { 'dir': '~/.fzf' }

" Other plugins
NeoBundle 'sjl/gundo.vim'
NeoBundle 'jlanzarotta/bufexplorer'
NeoBundle 'scrooloose/syntastic.git'
NeoBundle 'mileszs/ack.vim'
NeoBundle 'rking/ag.vim'
NeoBundle 'edsono/vim-matchit'
NeoBundle 'henrik/vim-indexed-search'
NeoBundle 'tpope/vim-abolish'
NeoBundle 'tpope/vim-repeat'
NeoBundle 'yukunlin/auto-pairs'
NeoBundle 'xolox/vim-session'
NeoBundle 'xolox/vim-misc'
NeoBundle 'godlygeek/tabular'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'rhysd/clever-f.vim'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'ervandew/supertab'
NeoBundle 'austintaylor/vim-commaobject'
NeoBundle 'tristen/vim-sparkup'
NeoBundle 'takac/vim-hardtime'
NeoBundle 'weierophinney/argumentrewrap'
NeoBundle 'joonty/vdebug'
NeoBundle 'shawncplus/Vim-toCterm'
"NeoBundle 'tpope/vim-eunuch'
NeoBundle 'tpope/vim-speeddating'
NeoBundle 'janko-m/vim-test'
NeoBundle 'mattn/webapi-vim.gi'
NeoBundle 'ryanoasis/vim-devicons'
NeoBundle 'Raimondi/delimitMate'
NeoBundle 'ashisha/image.vim'
NeoBundle 'junegunn/limelight.vim'

NeoBundle 'fatih/vim-go'
"NeoBundle 'klen/python-mode'
NeoBundle 'vim-scripts/c.vim'


call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
    " this will conveniently prompt you to install them.
NeoBundleCheck
" }}}

" Settings & Keybindings  ----------------------------------------------------------{{{
set expandtab tabstop=4 softtabstop=4 shiftwidth=4
set smarttab
set autoindent
set ruler rulerformat=%=%l/%L
set guicursor=a:blinkon0
set hidden
set ignorecase
set smartcase
set showcmd
set showmatch
set incsearch
set hls
set ls=2
set cursorline
set cursorcolumn
set nowrap
set backspace=2
set backspace=indent,eol,start
set shell=/bin/bash
set completeopt -=preview
set textwidth=100
set wildmenu
set wildmode=list:longest,full
set noshowmode
set cmdheight=1
set autoread
set foldlevel=1
set foldmethod=syntax
set nobackup
set noincsearch
set number numberwidth=4
set pastetoggle=<F3>
set scrolloff=4 sidescrolloff=10
set splitbelow
set splitright
set tabpagemax=20
set tags+=./tags.vendors,tags.vendors
set ttyfast
set mouse=a " Enable mouse
display=lastline
" }}}
